### ISSUE TITLE
Program start parsing mzML files but fails at the search step

### ISSUE THREAD

**Issue by k-p4** [markmipt/ms1searchpy#7]
Hello,

Thank you for the tool. I am interested in running some files. However, am consistently running into this error. I cannot find an error message in the code that allows me to troubleshoot this step. Any insight/help would be most appreciated.

Thank you.

```
(base) young@DataPC01:~/ms1searchpy$ ms1searchpy 20220418_KP_rTFEB_Trypsin_1_1_1.mzML -d P19484.fasta
     INFO: [19:06:25] Reading file 20220418_KP_rTFEB_Trypsin_1_1_1.mzML
     INFO: [19:06:35] Number of MS1 scans: 2358
     INFO: [19:06:35] Number of skipped MS1 scans: 0
    ERROR: [19:06:35] 'tof'
    ERROR: [19:06:35] Search is failed for file: 20220418_KP_rTFEB_Trypsin_1_1_1.mzML
```

The generated log files after each run attempt are empty.

**Comment by markmipt** [comment]
Hi,

Thanks for the interest in ms1searchpy and for the bug report. There were some missing parameters for feature detection algorithm and I've fixed it in the new ms1searchpy version (2.3.10, available at PyPi). Also, it could be also useful to update biosaur2 (0.1.8, available at PyPi).

Please let me know if it is helped. 

P.S. We usually prefer to run feature detection (biosaur2, Biosaur or Dinosaur) separately from ms1searchpy. It will save you time in case of reanalysis of the data, as well as give you some freedom in feature detection parameters.

**Comment by k-p4** [comment]
Hi,

I was able to re-run the file. Getting a different error this time:


```
ms1searchpy 20220418_KP_rTFEB_Trypsin_1_1_2.mzML -d P19484.fasta
<frozen importlib._bootstrap>:228: RuntimeWarning: scipy._lib.messagestream.MessageStream size changed, may indicate binary incompatibility. Expected 56 from C header, got 64 from PyObject
     INFO: [01:18:51] Reading file 20220418_KP_rTFEB_Trypsin_1_1_2.mzML
     INFO: [01:18:53] Number of MS1 scans: 2293
     INFO: [01:18:53] Number of skipped MS1 scans: 0
     INFO: [01:19:14] Detected number of hills: 341996
     INFO: [01:19:21] Number of potential isotope clusters: 58118
     INFO: [01:19:21] Average mass shift between monoisotopic and first 13C isotope: -0.276 ppm
     INFO: [01:19:21] Average mass std between monoisotopic and first 13C isotope: 0.581 ppm
     INFO: [01:19:21] Number of potential isotope clusters after smart mass accuracy for isotopes: 44462
     INFO: [01:19:22] Number of detected isotope clusters: 27602
     INFO: [01:19:23] Total number of peptide isotopic clusters: 27602
     INFO: [01:19:23] Number of peptide isotopic clusters passed filters: 25578
     INFO: [01:19:23] Running the search ...
     INFO: [01:19:23] Database information:
     INFO: [01:19:23] Target/Decoy proteins: 1/0
     INFO: [01:19:23] Target/Decoy peptides: 17/0
     INFO: [01:19:23] Target-Decoy peptide intersection: 0.0 %
Mean of empty slice.
invalid value encountered in double_scalars
     INFO: [01:19:23] Stage 0 search: probability of random match for theoretical peptide = nan
     INFO: [01:19:23] Stage 0 search: identified proteins = 1
     INFO: [01:19:23] Running mass recalibration...
     INFO: [01:19:23] Uncalibrated mass shift: 8.282 ppm
     INFO: [01:19:23] Uncalibrated mass sigma: 0.808 ppm
     INFO: [01:19:23] Estimated mass shift: 0.080 ppm
     INFO: [01:19:23] Estimated mass sigma: 0.609 ppm
Mean of empty slice.
invalid value encountered in double_scalars
     INFO: [01:19:23] Stage 1 search: probability of random match for theoretical peptide = nan
     INFO: [01:19:23] Stage 1 search: identified proteins = 1
     INFO: [01:19:23] Running RT prediction...
     INFO: [01:19:23] First-stage peptides used for RT prediction: 14
     INFO: [01:19:23] First-stage calibrated RT shift: 0.000 min
     INFO: [01:19:23] First-stage calibrated RT sigma: 0.000 min
     INFO: [01:19:23] Second-stage peptides used for RT prediction: 5
    ERROR: [01:19:23] Optimal parameters not found: Number of calls to function has reached maxfev = 1000.
    ERROR: [01:19:23] Search is failed for file: 20220418_KP_rTFEB_Trypsin_1_1_2.mzML
```

Before erroring out, I think the features.tsv file is written/populated (maybe partly)

Another question I had was regarding the how ms1searchpy handle proteases in arguments. My sample is Trypsin digested however I also have some Glu-C digests. Am I forgetting to supply an argument? 


Thanks!

**Comment by markmipt** [comment]
I see two issues here in your analysis:
1. Your database does not contain any decoy proteins. ms1searchpy requires it for FDR estimation and correct work. You should add the ‘-ad 1’ option to automatic generation of the decoy database by ms1searchpy.
2. And what is more crucial - your database contains only 1 protein. ms1searchpy was designed to deal with some statistical information and I’m note sure if it was ever tested for such small databases. However, it was successfully tested for samples containing a single protein (BSA, for example) but the search was done using a full swissprot database. Could you please try to add some extra proteins to your fasta file (at least known common contaminants, or maybe just the whole human swiss-prot) 

You can check output of “ms1searchpy -h” command for all available arguments. In particular, -e option is “cleavage rule in quotes!. X!Tandem style for cleavage rules: "[RK]|{P}" for trypsin, "[X]|[D]" for asp-n or "[RK]|{P},[K]|[X]" for mix of trypsin and lys-c (default: [RK]|{P})”. Thus, for the Glu-C you should add ‘-e  “[E]|[X]” ‘ option.

P.S. I can also try to analyze your data by myself if you share mzML and fasta with me (you can write directly at markmipt@gmail.com)
